### PR TITLE
indicate vis is the application; set title only

### PR DESCRIPTION
**Pull request by sewnie**
this changes the title to something along the lines of `vis /home/meow/src/vis-title/title.lua` or `vis [No Name]`

### CODE REVIEW

**Comment by sewnie** [comment]
as for the last commit:
```c
        case ']': /* OSC -- Operating System Command */
                switch (par) {
                case 0:
                        if (narg > 1) {
                                xsettitle(strescseq.args[1], 0);
                                xseticontitle(strescseq.args[1]);
                        }
                        return;
                case 1:
                        if (narg > 1)
                                xseticontitle(strescseq.args[1]);
                        return;
                case 2:
                        if (narg > 1)
                                xsettitle(strescseq.args[1], 0);
                        return;
```
before:
```
~ $ xprop
_NET_WM_ICON_NAME(UTF8_STRING) = "/home/meow/.config/vis/plugins/title.lua"
WM_ICON_NAME(UTF8_STRING) = "/home/meow/.config/vis/plugins/title.lua"
WM_STATE(WM_STATE):
...
```
after:
```
~ $ xprop
WM_STATE(WM_STATE):
```
> the WM_ICON_NAME property is an uninterpreted string that the client wants to be displayed in association with the window when it is iconified (for example, in an icon label). In other respects, including the type, it is similar to WM_NAME. For obvious geometric reasons, fewer characters will normally be visible in WM_ICON_NAME than WM_NAME.

**Comment by erf** [comment]
We could insert 'vis ' before the title, but i would drop the ":". Not sure about the importance of using "2" vs "0" - maybe you could explain / show the difference ? Also for this change only a single commit should be neccessary

**Comment by sewnie** [comment]
> Not sure about the importance of using "2" vs "0"

Read above.

> We could insert 'vis ' before the title, but i would drop the ":".

Understandable.

I've marked this PR as a draft as im currently working on solving #4

**Comment by erf** [comment]
I still don't understand the importance of your comments and i think it's linux spesific , not for macOS, which I'm using, so please explain to me

**Comment by sewnie** [comment]
`0` sets the title and icon.
`1` sets only the icon
`2` sets only the title

**Comment by sewnie** [comment]
does this work on macOS?

**Comment by erf** [comment]
i don't see any difference using 0 or 2. Not sure what icon is refered to. Is there a difference on Linux? Show a screenshot

**Comment by sewnie** [comment]
**The desktop environment will attempt to load this as the icon for the terminal, which is obviously invalid.**

And yes, there is a difference on Linux. I have this issue because my desktop environment reads that icon prop which is set to a text file, which obviously is not an icon.

**Comment by erf** [comment]
It still works OK on macOS so i guess it's OK to merge this.

**Comment by sewnie** [comment]
if you want further evidence, Vim uses the same `2`:
https://github.com/vim/vim/blob/67abf1592c83c910c7815478f67e0a8989d51417/src/term.c#L463

**Pull request merged**
